SELECT *
FROM XROLLPRODRG
WHERE PROFILEID = 'AZ48' AND PRODUCTID='48   AZ  -10' AND ROLLGRADE='610';
--FOR UPDATE;

SELECT *
FROM XROLLPROF
WHERE PROFILEID = 'AZ48';
--FOR UPDATE

SELECT *
FROM XROLLPROD
WHERE PROFILEID = 'AZ48' AND PRODUCTID='48   AZ  -10';
--FOR UPDATE;

SELECT *
FROM Glo_Ipcdisp
where PROCNAME='PSI_CYCLIC';

SELECT *
FROM Glo_Timer where MANAGER='PSI_CYCLIC';
