SELECT owner, directory_name, directory_path 
FROM all_directories;

--
SELECT *
FROM XROLLPRODRG;

--
SELECT *
FROM XROLLPRODRG t1
WHERE VERSION = (
    SELECT MAX(VERSION)
    FROM XROLLPRODRG t2
    WHERE t2.PROFILEID = t1.PROFILEID
      AND t2.PRODUCTID = t1.PRODUCTID
      AND t2.ROLLGRADE = t1.ROLLGRADE
);

--
SELECT count(*)
FROM XROLLPRODRG t1
WHERE (PROFILEID, PRODUCTID, ROLLGRADE) IN (
    SELECT PROFILEID, PRODUCTID, ROLLGRADE
    FROM XROLLPRODRG
    GROUP BY PROFILEID, PRODUCTID, ROLLGRADE
    HAVING COUNT(*) > 1
);
