-- this last
SELECT * 
FROM XROLLPRODRG
WHERE PROFILEID='AL13' AND PRODUCTID='13770AZ' AND ROLLGRADE='381';
--WHERE PROFILEID='AU16' AND PRODUCTID='16   AU' AND ROLLGRADE='560';
--FOR UPDATE;

-- this second
SELECT*
FROM XROLLPROD
WHERE PROFILEID='AU16' AND PRODUCTID='16   AU';
--FOR UPDATE;

-- this first
SELECT *
FROM XROLLPROF
WHERE PROFILEID='AU16';
--FOR UPDATE;
